const INVOICE_STATUSES = ["OVERDUE", "FAILED", "RECOVERED", "PENDING"];
const PAYMENT_METHODS = ["CARD", "BANK_TRANSFER"];
const AUDIT_STATUSES = ["SUCCESS", "BLOCKED_BY_GUARDRAIL"];

const RECOVERY_ACTIONS = [
  "SEND_WHATSAPP_REMINDER",
  "RETRY_CARD",
  "SEND_PAYMENT_LINK",
  "TRIGGER_AI_VOICE_CALL",
  "ESCALATE_TO_ADMIN",
  "PAUSE_PROMISE_TO_PAY",
];

const CONFIDENCE_THRESHOLD = Number(process.env.CONFIDENCE_THRESHOLD || 0.85);
const MAX_RETRIES = Number(process.env.MAX_RETRIES || 3);

module.exports = {
  INVOICE_STATUSES,
  PAYMENT_METHODS,
  AUDIT_STATUSES,
  RECOVERY_ACTIONS,
  CONFIDENCE_THRESHOLD,
  MAX_RETRIES,
};
